CREATE DATABASE [_dba]
GO
ALTER DATABASE [_dba] SET RECOVERY SIMPLE; 
ALTER DATABASE [_dba] SET RESTRICTED_USER;
GO

USE [_dba]
GO

ALTER AUTHORIZATION ON DATABASE::[_DBA] TO [sa];
ALTER DATABASE SCOPED CONFIGURATION SET MAXDOP = 1;
ALTER DATABASE SCOPED CONFIGURATION SET QUERY_OPTIMIZER_HOTFIXES = ON;
GO
